### ISSUE TITLE
sorta small bug

### ISSUE THREAD

**Issue by ivannunyadambiz** [sparkfun/SparkFun_PCA9536_Arduino_Library#4]
```
if (pin > 4)
        return PCA9536_ERROR_UNDEFINED;
```

should be 
```
if (pin > 3)
        return PCA9536_ERROR_UNDEFINED;
```

probably won't stop it from working, but you won't be able to write to pin '4' as it does not exist

**Comment by PaulZC** [comment]
Hi @ivannunyadambiz ,

Good catch - thank you! Corrected in [v1.2.2](https://github.com/sparkfun/SparkFun_PCA9536_Arduino_Library/releases/tag/v1.2.2).

Best wishes,
Paul
